global:
  chartName: products
products:
  # Deployment object
  deployment:
    enabled: true
    name: products
    namespace: ecommerce
    replicas: 3
    appName: products
    role: api
    containerName: products-container
    imageRepository: 798842239772.dkr.ecr.us-east-1.amazonaws.com/ecommerce-products
    imageTag: 0.0.0
    port: 3004
  # Updated (New) Deployment resource
  newDeployment:
    enabled: false
  # Stable Service object
  service:
    enabled: true
    name: products-service
    namespace: ecommerce
    appName: products
    type: ClusterIP
    servicePort: 3004
    targetPort: 3004
  # Canary Service object
  canaryService:
    enabled: false
  # Service Account object
  serviceAccount:
    enabled: true
    name: products-service-account
    namespace: ecommerce
  # Namespace object
  namespace:
    enabled: false
  # Ingress 
  ingress:
    enabled: false
  # Horizontal Pod Autoscaler
  hpa:
    enabled: false
  # Canary Rollout
  canaryRollout:
    enabled: false
$APP:
  deployment:
    imageTag: 0.1.0
