name: Promote products from develop to staging

on:
  push:
    branches:
      - main
    paths:
      - envs/develop/products-version.yaml

permissions:
  contents: write
  pull-requests: write

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create new branch to do changes
        run: |
          # configure git client
          git config user.email "luis.longo.m@gmail.com"
          git config user.name "luisllm"

          # create a new branch
          git switch -c staging/${{ github.sha }}

          # promote the change
          cp envs/develop/products-version.yaml envs/staging/products-version.yaml

          # push the change to the new branch
          git add envs/staging/products-version.yaml
          git commit -m "Promote develop to staging"
          git push -u origin staging/${{ github.sha }}

      - name: Create Pull Request with the changes        
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: |
          gh pr create \
            -B main \
            -H staging/${{ github.sha }} \
            --title "Promote develop to staging" \
            --body "Automatically created by GitHub Actions"
